# Render YAML Configuration

# This configuration file is used to define the deployment process on Render.

services:
  - type: web
    name: bot-albions
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    cleanCommand: "npm prune --production"
    projects:
      - path: .
        type: nodejs
